### ISSUE TITLE
why DefaultConnectionManager and ProcessorManager use  ArrayBlockingQueue

### ISSUE THREAD

**Issue by huangyunbin** [alipay/sofa-rpc#215]
I think LinkedBlockingQueue is better.

LinkedBlockingQueue use two lock,ArrayBlockingQueue use one lock. LinkedBlockingQueue performance is better。

because ArrayBlockingQueue is good for gc？ 

but UserThreadPool and BusinessPool use ThreadPoolUtils is LinkedBlockingQueue,
AllConnectConnectionHolder and TimeWindowRegulator also use LinkedBlockingQueue.

**Comment by xmtsui** [comment]
We indeed have not paid lot attention of this, because during our load test, ArrayBlockingQueue and LinkedBlockingQueue reach the same bottle neck for rpc sync invoke scenario, which means the performance of the two blocking queue differs not that much for online applications.

If you have more detail test, we'd be glad to hear and take this into account. @huangyunbin

**Comment by leizhiyuan** [comment]
@huangyunbin If there was no question, I will close this issue, you can reopen it later.
